config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :applications, except: [:show]

  get 'application/:id', to: 'applications#show', as: 'application_show'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application.rb
class Application < ApplicationRecord
    include Placeholder

    has_many :technologies
    accepts_nested_attributes_for :technologies, 
                                  reject_if: lambda { |attr| attr['name'].blank? }

    validates_presence_of :title, :image, :thumbnail, :body

    def self.ember
        where(subtitle: "Ember.js")
    end

    scope :ruby_on_rails, -> { where(subtitle: "Ruby on Rails")}

    after_initialize :set_defaults

    def set_defaults
        self.image ||= Placeholder.image_generator(height: '600', width: '400')
        self.thumbnail ||= Placeholder.image_generator(height: '350', width: '200')
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include DeviseWhitelist
  include SetSource
  include CurrentUserConcern
  include DefaultPageContent
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
    before_action :set_application, only: [:show, :edit, :update, :destroy]
    layout "applications"

    access all: [:show, :index], user: { except: [:new, :create, :update, :edit, :destroy] }, site_admin: :all
    # Index route
    def index
        # Get all of the applications
        @applications = Application.all
    end

    # Show Route
    def show
    end

    # New Route for the Application form
    def new
        @application = Application.new
        3.times { @application.technologies.build }
    end

    # Create Method for creating a new Application
    def create
        @application = Application.new(application_params)

        respond_to do |format|
            if @application.save
                format.html { redirect_to applications_path, notice: 'Your Application has been Created.'}
            else
                format.html { render :new }
            end
        end
    end

    # Edit Route
    def edit
      3.times { @application.technologies.build }
    end

    def update
        respond_to do |format|
            if @application.update(application_params)
                format.html { redirect_to applications_path, notice: 'Your Application has been Updated.'}
            else
                format.html { render :edit }
            end
        end
    end

    def destroy
        @application.destroy
        respond_to do |format|
            format.html { redirect_to applications_path, notice: "Your Application has been Deleted."}
        end
    end

    private
        def set_application
            @application = Application.find(params[:id])
        end

        def application_params
            params.require(:application).permit(
                :title,
                :subtitle,
                :thumbnail,
                :image,
                :body,
                technologies_attributes: [:name]
            )
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def login_helper
    if current_user.is_a?(GuestUser)
      (link_to "Login", new_user_session_path) + " " +
      (link_to "Register", new_user_registration_path)
    else
      link_to "Logout", destroy_user_session_path, method: :delete
    end
  end

  def source_helper
    if session[:source]
      greeting = "Thanks for visiting me from #{session[:source]}"
      content_tag(:p, greeting, class: "source-greeting")
    end
  end

  def copyright_generator
    BarnesViewTool::Renderer.copyright("Tevin Mantock", "All Rights Reserved")
  end
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/views/applications/_app.html.erb
<div>
    <%= image_tag app.thumbnail unless app.thumbnail.nil? %>
    <h3><%= link_to app.title, application_show_path(app) %></h3>
    <h4><%= app.subtitle %></h4>
    <%= link_to "Edit Application", edit_application_path(app) if logged_in?(:site_admin) %>
</div>

app/views/applications/_form.html.erb
<%= form_with(model: application, local: true) do |form| %>
    <div class="field">
      <%= form.label :title %>
      <%= form.text_field :title, id: :application_title %>
    </div>

    <div class="field">
        <%= form.label :subtitle %>
        <%= form.text_field :subtitle, id: :application_title %>
    </div>

    <div class="field">
        <%= form.label :thumbnail %>
        <%= form.text_field :thumbnail, id: :application_thumbnail %>
    </div>

    <div class="field">
        <%= form.label :image %>
        <%= form.text_field :image, id: :application_image %>
    </div>

    <div class="field">
      <%= form.label :body %>
      <%= form.text_area :body, id: :application_body %>
    </div>

    <ul>
      <%= form.fields_for :technologies do |tech| %>
        <li>
          <%= tech.label :name %>
          <%= tech.text_field :name%>
        </li>
      <% end %>
    </ul>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>

app/views/applications/edit.html.erb
<h1>Edit Application <%= @application.title %></h1>
<%= render "form", application: @application %>

app/views/applications/index.html.erb
<h1>Applications</h1>

<p id="notice"><%= notice %></p>

<%= link_to "Create New Application", new_application_path if logged_in?(:site_admin) %>

<%= render partial: 'app', collection: @applications %>

app/views/applications/new.html.erb
<h1>Create a new Application</h1>
<%= render "form", application: @application %>

app/views/applications/show.html.erb
<div>
    <%= image_tag @application.image unless @application.image.nil? %>
    <h1><%= @application.title %></h1>
    <em><%= @application.subtitle %></em>
    <p><%= @application.body %></p>
    <%= link_to "Edit Application", edit_application_path(@application) if logged_in?(:site_admin)%>
    <%= link_to "Delete Application", @application, method: :delete, data: { confirm: "Are you sure" } if logged_in?(:site_admin)%>
    <h2>Tech Used</h2>
    <% @application.technologies.each do |tech| %>
    	<p> <%= tech.name %> </p>
	<% end %>
</div>